#ifndef _COMMON_HASH_H__
#define _COMMON_HASH_H__
#define HASH_KEY_SIZE 64
#define MESSAGE_SIZE 256
#define ACCOUNT_SIZE 15
#define ACCOUNT_LEN 10
#define TIME_SIZE 20
#define GROUP_SIZE 25
#define GROUP_LEN 20

/* 状态码 */
enum STATUS_CODE
{
    NOT_SEARCH = -1,
    ON_SUCCESSS,
    SEARCH_SUCCESS,
    NULL_PTRR,
    MALLOC_ERRORR,
    INVALID_ACCESSS,
};
#endif //_COMMON_HASH_H__